version: '3.4'
services:
    garie-webscore:
        build: .
        privileged: true
        ports:
            - 3000:3000
        environment:
            - USERNAME=admin
            - PASSWORD=admin
            - TEST_SUBSCRIPTION_EVENTS=false
        depends_on:
            - mailtrap
            - influxdb

    mailtrap:
        image: eaudeweb/mailtrap
        environment:
            - MT_USER=mailtrap
            - MT_PASSWD=mailtrap
        ports:
            - 2000:80
    influxdb:
        image: 'influxdb:latest'
        ports:
            - 8086:8086
        environment:
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=admin